{
 "title": "Changement Climatique",
 "description": "Données relatives au changement climatique",
 "time": { "from": "1993-01-01T00:00:00.000Z", "to": "2023-01-01T00:00:00.000Z" },
 "panels": [
  { "title": "Indicateurs globaux", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "7) Émissions de GES par Habitant par Pays",
   "type": "geomap",
   "description": "Émissions de GES par habitant par pays (dernière mesure disponible)",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "6) Part de la Superficie Forestière",
   "type": "geomap",
   "description": "Part de la superficie forestière (dernière mesure disponible)",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "1) Concentration Atmosphérique de CO2",
   "type": "timeseries",
   "description": "Evolution de la concentration atmosphérique de CO2 entre 01-02-1958 et 01-04-2023",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"climate-change\")\n  |> range(start: 1958-02-01T01:00:00Z, stop: 2023-04-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"atmospheric-co2-concentration\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "5) Décompte des Catastrophes Naturelles par Type",
   "type": "stat",
   "description": "Décompte des catastrophes naturelles par type (dernière mesure disponible)",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "query": "from(bucket: \"climate-change\")\n  |> range(start: 1980-01-01T00:00:00Z, stop: 2022-02-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"climate-disasters-frequency\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> last()\n  |> group(columns: [\"indicator\"])\n  |> sum()"
    }
   ]
  },
  {
   "title": "3) Variation du Niveau Moyen de la Mer",
   "type": "timeseries",
   "description": "Changement du niveau moyen de la mer entre 01-11-1992 et 01-12-2022",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "from(bucket: \"climate-change\")\n  |> range(start: 1992-11-01T00:00:00Z, stop: 2022-12-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"mean-sea-levels-change\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  { "title": "Indicateurs locaux (France)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "4) Émissions de GES en France",
   "type": "timeseries",
   "description": "Émissions de GES en france entre 01-12-1980 et 01-02-2020",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "query": "from(bucket: \"climate-change\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: 2020-02-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"ghg-emissions\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.country == \"France\")\n  |> map(fn: (r) => ({ r with _value: r._value * 1000000.0 }))"
    }
   ]
  },
  {
   "title": "10) Catastrophe Naturelle la Plus Fréquente en France par Période de 5 ans en France",
   "type": "table",
   "description": "Catastrophe naturelle la plus fréquente en france par période de 5 ans en France entre 01-12-1979 et 01-02-2022",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"climate-change\")\n  |> range(start: 1980-01-01T00:00:00Z, stop: 2022-02-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"climate-disasters-frequency\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.country == \"France\")\n  |> window(every: 5y)\n  |> group(columns: [\"disaster_type\", \"_start\", \"_stop\"])\n  |> sum()\n  |> group(columns: [\"_start\", \"_stop\"])\n  |> top(n: 1, columns: [\"_value\"])\n  |> map(fn: (r) => ({\n      _value: r._value,\n      start_period: r._start,\n      end_period: r._stop,\n      most_frequent_type: r.disaster_type,\n      _time: r._stop\n    })\n  )\n  |> sort(columns: [\"_time\"], desc: true)"
    }
   ]
  },
  {
   "title": "9) Année Record de l'Augmentation de Température en France par Période de 5 ans",
   "type": "table",
   "description": "Année record de l'augmentation de température en France par période de 5 ans entre 01-12-1960 et 01-02-2022",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"climate-change\")\n  |> range(start: 1960-12-01T00:00:00Z, stop: 2022-02-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"annual-surface-temperature-change\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.country == \"France\")\n  |> window(every: 5y)\n  |> max()\n  |> map(fn: (r) => ({\n      start_period: r._start,\n      end_period: r._stop,\n      hottest_year: r._time,\n      temperature: r._value,\n      _time: r._time\n    })\n  )\n  |> sort(columns: [\"_time\"], desc: true)"
    }
   ]
  },
  {
   "title": "2) Evolution de la Température de Surface en France",
   "type": "timeseries",
   "description": "Evolution de la température de surface en France entre 01-12-1960 et 01-02-2022 ",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"climate-change\")\n  |> range(start: 1960-12-01T00:00:00Z, stop: 2022-02-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"annual-surface-temperature-change\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.country == \"France\")"
    }
   ]
  },
  {
   "title": "8) Décomposition de l'Occupation du Sol Français ",
   "type": "piechart",
   "description": "Décomposition de l'occupation du sol français (dernière mesure disponible)",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "hectares" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"climate-change\")\n  |> range(start: 1992-01-01T00:00:00Z, stop: 2020-02-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"land-cover-accounts\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.country == \"France\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value * 1000.0 }))"
    }
   ]
  },
  {
   "title": "Notices & Droits d'Auteur",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 71 },
   "options": {
    "content": "Ce TP utilise les datasets [Climate Change Data](https://climatedata.imf.org/pages/climatechange-data) fourni par l'[IMF](https://imf.org/) et [CO2 and Greenhouse Gas Emissions](https://ourworldindata.org/co2-and-greenhouse-gas-emissions) fourni par [Our World In Data](https://ourworldindata.org/). Le dataset [CO2 and Greenhouse Gas Emissions](https://ourworldindata.org/co2-and-greenhouse-gas-emissions) est téléchargeable sur [GitHub](https://github.com/owid/co2-data)\n\nCopyright DWWM EPSI ONLINE"
   }
  }
 ]
}